# Site settings
title: Capital Beards
email: contact@capitalbeards.org.uk
description: 'The Capital Beards, the London thatch of The British Beard Club'
html_description: The London thatch of <a href="http://thebritishbeardclub.org">The British Beard Club</a>
baseurl: ""
url: "http://capitalbeards.org.uk"
username: capitalbeards

# Build settings
markdown: redcarpet
permalink: pretty
exclude : ['vendor', 'Gemfile*', 'bin', 'README.md']
